[pytest]
markers =
    Smoke: This is for smoke test cases execution
    Sanity: This is for Sanity test cases execution
    TopPriority: This is for TopPriority test cases execution
    Regression: This is for Regression test cases execution
    Mandatory: This is for Mandatory test cases execution
    Assertions: for Asserstions tag